version: 2
machine:
  services:
    - docker
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
      - image: postgres:9.6
         environment:
         - POSTGRES_USER=judge
         - POSTGRES_DB=judgeapi
         - POSTGRES_PASSWORD=judge
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Docker Compose
          command: |
            cp judgeapi-travis.env .env
            docker-compose -p judgecompose up -d
      - run:
          name: Build Tests
          command: |
            docker build test_docker -t judgecompose_test
      - run:
          name: Run Tests
          command: docker run -t --network=judgecompose_default judgecompose_test:latest
